### ISSUE TITLE
rockemq-flink: RocketMQSource will throw a NullPointerException 

### ISSUE THREAD

**Issue by SuXingLee** [apache/rocketmq-externals#152]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
run a flink application with checkpoint
RocketMQSource will throw  a NullPointerException when rocketmq do rebalance or restart flink's task .

- What did you expect to see?
fix this NPE.

- What did you see instead?
```
2018-11-12 09:20:49,034 ERROR RocketmqClient                                                - doPullTask Exception
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.rocketmq.flink.RocketMQSource$1.doPullTask(RocketMQSource.java:209)
        at com.alibaba.rocketmq.client.consumer.MQPullConsumerScheduleService$PullTaskImpl.run(MQPullConsumerScheduleService.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.rocketmq.flink.RocketMQSource.getMessageQueueOffset(RocketMQSource.java:261)
        at org.apache.rocketmq.flink.RocketMQSource.access$000(RocketMQSource.java:55)
        at org.apache.rocketmq.flink.RocketMQSource$1.doPullTask(RocketMQSource.java:140)
        ... 8 more
```
2. Please tell us about your environment:
Flink 1.5.5

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
#

**Comment by SuXingLee** [comment]
#153
