### ISSUE TITLE
Caused by:  /root/logs/rocketmqlogs/rocketmq_client.log (No such file or directory)

### ISSUE THREAD

**Issue by gouez** [apache/rocketmq-externals#227]
运行4.4版本下面play-docker.sh脚本，启动报错
`java.io.FileNotFoundException: /root/logs/rocketmqlogs/rocketmq_client.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.rocketmq.logging.inner.LoggingBuilder$FileAppender.setFile(LoggingBuilder.java:697)
        at org.apache.rocketmq.logging.inner.LoggingBuilder$RollingFileAppender.setFile(LoggingBuilder.java:820)
        at org.apache.rocketmq.logging.inner.LoggingBuilder$FileAppender.activateOptions(LoggingBuilder.java:639)
        at org.apache.rocketmq.logging.inner.LoggingBuilder$AppenderBuilder.withRollingFileAppender(LoggingBuilder.java:104)
        at org.apache.rocketmq.client.log.ClientLogger.createClientAppender(ClientLogger.java:75)
        at org.apache.rocketmq.client.log.ClientLogger.createLogger(ClientLogger.java:89)
        at org.apache.rocketmq.client.log.ClientLogger.<clinit>(ClientLogger.java:52)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:64)
        at org.apache.rocketmq.client.producer.DefaultMQProducer.<init>(DefaultMQProducer.java:183)
        at org.apache.rocketmq.example.quickstart.Producer.main(Producer.java:34)
14:54:16.637 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, TopicTest
See http://rocketmq.apache.org/docs/faq/ for further details.`

**Comment by walking98** [comment]
have you ever tried to mk local dirs (docker volume)?
mkdir -p `pwd`/data/broker/logs
mkdir -p `pwd`/data/broker/store

@gouez

**Comment by vongosling** [comment]
@gouez please check using the latest source
