### ISSUE TITLE
rocketmq-console compile error and roles no effective

### ISSUE THREAD

**Issue by zyhui98** [apache/rocketmq-externals#310]
**BUG REPORT**

1. Please describe the issue you observed:

a、idea编译是，WebUtil类报错，HttpServletRequest等类不能引入
b、user.properties,设置权限无效

2. Please tell us about your environment:
IDEA、Java8

**Comment by zyhui98** [comment]
java.util.concurrent.RejectedExecutionException: Task org.apache.rocketmq.broker.out.BrokerOuterAPI$1@6ca7fb31 rejected from org.apache.rocketmq.broker.latency.BrokerFixedThreadPoolExecutor@6a7fd163[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)

这个报错怎么解决

**Comment by zyhui98** [comment]
错误: 找不到或无法加载主类 @{failsafeArgLine}
