### ISSUE TITLE
[rocketmq-connect-runtime]error:RROR ConsumeMessageThread_1 - persist file ...config/position.json exception

### ISSUE THREAD

**Issue by ClementIV** [apache/rocketmq-externals#491]
我启动两个或者三个runtime后 那个postion.json会持续被删除重写，导致其他runtime找不到该文件

```java
ERROR ConsumeMessageThread_1 - persist file /Users/yongqifeng/connectorStore/config/position.json exception
java.io.FileNotFoundException: /Users/yongqifeng/connectorStore/config/position.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_221]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_221]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_221]
	at org.apache.rocketmq.connect.runtime.utils.FileAndPropertyUtil.file2String(FileAndPropertyUtil.java:89) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.FileAndPropertyUtil.file2String(FileAndPropertyUtil.java:79) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.FileAndPropertyUtil.string2File(FileAndPropertyUtil.java:45) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.store.FileBaseKeyValueStore.persist(FileBaseKeyValueStore.java:123) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.PositionManagementServiceImpl.persist(PositionManagementServiceImpl.java:88) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.PositionManagementServiceImpl$PositionChangeCallback.onCompletion(PositionManagementServiceImpl.java:137) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.PositionManagementServiceImpl$PositionChangeCallback.onCompletion(PositionManagementServiceImpl.java:131) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.utils.datasync.BrokerBasedLog$MessageListenerImpl.consumeMessage(BrokerBasedLog.java:193) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:411) [rocketmq-client-4.5.2.jar:4.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

```

The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ClementIV** [comment]
runtime配置问题
