### ISSUE TITLE
[GSoC 2020 rocketmq-connect-runtime enhancement] possible enhancements recorder

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#540]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).
**FEATURE REQUEST**
This is a recorder for  issues I've met when deploying rocketmq-connect-runtime, and there are not many core-related or performance enhancements I can observe now, so I'll just put some simple enhancements as candidates.

- [ ] runtime stopAll doesn't stop immediately, log system still outputs stale messages
- [ ] The log systems are printing some very detailed logs, we can enhance the log system of runtime by providing multiple log levels so developers/users can pick the right amount of logs needed to debug/develop/troubleshooting.
- [ ] fix up typos along developing
- [ ] jdbc sink connector is observing route topic changes, but I intuitively feel this dynamic routing management can be moved to runtime, need to discuss with mentors.
- [ ] currently if user wants to change a connector configuration, they need to use either web browser or `curl` command. However if user use `curl` command they need to encode the config json to a url-encoded format. We could write some simple script or CLI to help user deploy connectors more easily, for example it will probably look like `rcadmin createConnector -n <NAME> -f jdbc-sink-connector-config.json`

**Comment by imaffe** [comment]
Trying to debug why rebalance service is trying to create new task with a deleted task configuration for both source and sink connectors.
```
020-04-01 01:35:53 INFO RebalanceService - Allocated connector:{jdbc-source-connector=ConnectKeyValue{properties={dbPort=3306, mode=bulk, source-record-converter=org.apache.rocketmq.connect.runtime.converter.JsonConverter, dbUsername=root, whiteDataBase={"jdbc":{"person":{"NO-FILTER":"10"}}}, connector-class=org.apache.rocketmq.connect.jdbc.connector.JdbcSourceConnector, rocketmqTopic=jdbcTopic, dbUrl=127.0.0.1, update-timestamp=1585673844225, dbPassword=root}}, cassandra-sink-connector=ConnectKeyValue{properties={dbPort=9042, mode=bulk, source-record-converter=org.apache.rocketmq.connect.runtime.converter.JsonConverter, dbUsername=cassandra, source-cluster=127.0.0.1, connector-class=org.apache.rocketmq.connect.cassandra.connector.CassandraSinkConnector, source-rocketmq=127.0.0.1:9876, rocketmqTopic=jdbcTopic, dbUrl=127.0.0.1, update-timestamp=1585673844285, dbPassword=cassandra}}}
2020-04-01 01:35:53 INFO RebalanceService - Allocated task:{jdbc-source-connector=[ConnectKeyValue{properties={update-timestamp=1585672986959, config-deleted=1}}], cassandra-sink-connector=[ConnectKeyValue{properties={update-timestamp=1585672986959, config-deleted=1}}]}
2020-04-01 01:35:53 INFO RebalanceService - Add new tasks,connector name jdbc-source-connector, config ConnectKeyValue{properties={update-timestamp=1585672986959, config-deleted=1}}
2020-04-01 01:35:53 INFO RebalanceService - Add new tasks,connector name cassandra-sink-connector, config ConnectKeyValue{properties={update-timestamp=1585672986959, config-deleted=1}}
2020-04-01 01:35:53 ERROR RebalanceService - RebalanceImpl#updateProcessConfigsInRebalance start connector or task failed
java.lang.NullPointerException: null
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_242]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_242]
	at org.apache.rocketmq.connect.runtime.connectorwrapper.Worker.startTasks(Worker.java:279) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.RebalanceImpl.updateProcessConfigsInRebalance(RebalanceImpl.java:100) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.RebalanceImpl.doRebalance(RebalanceImpl.java:88) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.service.RebalanceService.run(RebalanceService.java:63) [rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

**Comment by imaffe** [comment]
We (me and @gripson) found  a bug in jdbc-connector. when creating DruidDataSource

in `DBUtils.java`

```

        Map<String, String> map = new HashMap<>();
        map.put("driverClassName", "com.mysql.cj.jdbc.Driver");
        map.put("url",
                "jdbc:mysql://" + config.getDbUrl() + ":" + config.getDbPort()  + "?useSSL=false&verifyServerCertificate=false&serverTimezone=GMT%2B8&characterEncoding=utf8");
        map.put("username", config.getDbUsername());
        map.put("password", config.getDbPassword());
        map.put("initialSize", "1");
        map.put("maxActive", "2");
        map.put("maxWait", "60000");
        map.put("timeBetweenEvictionRunsMillis", "60000");
        map.put("minEvictableIdleTimeMillis", "300000");
        map.put("validationQuery", "SELECT 1");
        map.put("testWhileIdle", "true");
        log.info("{} config read successful", map);
        DataSource dataSource = DruidDataSourceFactory.createDataSource(map);
        log.info("created data source");

...
```

Here the datasource creation could fail. We are trying to find out why createDataSource would fail.

My source connector configuration:
```
{
    "connector-class":"org.apache.rocketmq.connect.jdbc.connector.JdbcSourceConnector",
    "rocketmqTopic":"jdbcTopic",
    "dbUrl":"127.0.0.1",
    "dbPort":"3306",
    "dbUsername":"root",
    "dbPassword":"root",
    "whiteDataBase": {
        "jdbc":{
           "person": {"NO-FILTER": "10"}
         }
      },
    "mode": "bulk",
    "task-parallelism": 1,
    "source-cluster": "172.17.0.1:10911",
    "source-rocketmq": "localhost:9876",
    "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"
 }

```

**Comment by gripson** [comment]
> We (me and @gripson) found a bug in jdbc-connector. when creating DruidDataSource
> 
> in `DBUtils.java`
> 
> ```
> 
>         Map<String, String> map = new HashMap<>();
>         map.put("driverClassName", "com.mysql.cj.jdbc.Driver");
>         map.put("url",
>                 "jdbc:mysql://" + config.getDbUrl() + ":" + config.getDbPort()  + "?useSSL=false&verifyServerCertificate=false&serverTimezone=GMT%2B8&characterEncoding=utf8");
>         map.put("username", config.getDbUsername());
>         map.put("password", config.getDbPassword());
>         map.put("initialSize", "1");
>         map.put("maxActive", "2");
>         map.put("maxWait", "60000");
>         map.put("timeBetweenEvictionRunsMillis", "60000");
>         map.put("minEvictableIdleTimeMillis", "300000");
>         map.put("validationQuery", "SELECT 1");
>         map.put("testWhileIdle", "true");
>         log.info("{} config read successful", map);
>         DataSource dataSource = DruidDataSourceFactory.createDataSource(map);
>         log.info("created data source");
> 
> ...
> ```
> 
> Here the datasource creation could fail. We are trying to find out why createDataSource would fail.
> 
> My source connector configuration:
> 
> ```
> {
>     "connector-class":"org.apache.rocketmq.connect.jdbc.connector.JdbcSourceConnector",
>     "rocketmqTopic":"jdbcTopic",
>     "dbUrl":"127.0.0.1",
>     "dbPort":"3306",
>     "dbUsername":"root",
>     "dbPassword":"root",
>     "whiteDataBase": {
>         "jdbc":{
>            "person": {"NO-FILTER": "10"}
>          }
>       },
>     "mode": "bulk",
>     "task-parallelism": 1,
>     "source-cluster": "172.17.0.1:10911",
>     "source-rocketmq": "localhost:9876",
>     "source-record-converter":"org.apache.rocketmq.connect.runtime.converter.JsonConverter"
>  }
> ```

We (@imaffe and I) realized this issue is because of lack of `rocketmq-connect-jdbc-0.0.1-SNAPSHOT-jar-with-dependencies.jar` since we did not copy it to the `pluginPaths` after building jdbc connector

**Comment by imaffe** [comment]
Recorder: a possible cause for `stopAll` not working here,`connectorConfig` declared but not used.
```
    @Override
    public void removeConnectorConfig(String connectorName) {

        ConnectKeyValue config = new ConnectKeyValue();
        config.put(RuntimeConfigDefine.UPDATE_TIMESATMP, System.currentTimeMillis());
        config.put(RuntimeConfigDefine.CONFIG_DELETED, 1);
        // TODO connectorConfig is not being used
        Map<String, ConnectKeyValue> connectorConfig = new HashMap<>();
        connectorConfig.put(connectorName, config);
        List<ConnectKeyValue> taskConfigList = new ArrayList<>();
        taskConfigList.add(config);

        connectorKeyValueStore.put(connectorName, config);
        putTaskConfigs(connectorName, taskConfigList);
        sendSynchronizeConfig();
    }
```

**Comment by imaffe** [comment]
Another place that cause `fetch topicList error` after `stopAll` command is that in jdbc sink connector is not stoped properly. The `stopAll` relies on each connector's `stop` method, but in jdbc sink connector the `startListener()` method created a scheduled task but was not cancelled in the `stop()` method.  Similarly when the `srcMQAdminExt.shutdown()` was called the listener is still running. 
```
    public void startListener() {
        listenerHandle = executor.scheduleAtFixedRate(new Runnable() {
            boolean first = true;
            HashMap<String, Set<TaskTopicInfo>> origin = null;

            @Override
            public void run() {
                buildRoute();
                if (first) {
                    origin = CloneUtils.clone(topicRouteMap);
                    first = false;
                }
                if (!compare(origin, topicRouteMap)) {
                    context.requestTaskReconfiguration();
                    origin = CloneUtils.clone(topicRouteMap);
                }
            }
        }, ((SinkDbConnectorConfig) dbConnectorConfig).getRefreshInterval(), ((SinkDbConnectorConfig) dbConnectorConfig).getRefreshInterval(), TimeUnit.SECONDS);
    }
```
A direct solution would be like cancel the scheduled task on stop() method :
```
private ScheduledFuture<?> listenerHandle;
... 
    @Override
    public void stop() {
        listenerHandle.cancel(true);
        // srcMQAdminExt.shutdown();
    }
```
But in the long run we might need to refactor the `listener` code. Will be working on it

**Comment by imaffe** [comment]
In runtime `WorkerSinkTask`, in the main run method
```
            while (!isStopping.get()) {
                // TODO if isStopping == False then entered this section
                pullMessageFromQueues();
            }
```
and a `stop()` method where isStopping is an AtomicBoolean.
```
    public void stop() {
        isStopping.set(true);
        consumer.shutdown();
        sinkTask.stop();
    }
```



However there could be a TOCTOU race condition, when pullMessageFromQueues is about to be executed, and then consumer.shutdown() is called, then pullMessageFromQueues is executed, result in the exception.

```
Run task failed.
org.apache.rocketmq.client.exception.MQClientException: The consumer is not in running status, SHUTDOWN_ALREADY
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPullConsumerImpl.isRunning(DefaultMQPullConsumerImpl.java:105) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPullConsumerImpl.pullSyncImpl(DefaultMQPullConsumerImpl.java:228) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.impl.consumer.DefaultMQPullConsumerImpl.pullBlockIfNotFound(DefaultMQPullConsumerImpl.java:529) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.consumer.DefaultMQPullConsumer.pullBlockIfNotFound(DefaultMQPullConsumer.java:364) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.connect.runtime.connectorwrapper.WorkerSinkTask.pullMessageFromQueues(WorkerSinkTask.java:272) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at org.apache.rocketmq.connect.runtime.connectorwrapper.WorkerSinkTask.run(WorkerSinkTask.java:262) ~[rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]


```

Simply use synchronized might damage performance, but I can't think of a "mainstream" solution to this, would appreciate If someone can teach me how to handle this situation properly.

**Comment by imaffe** [comment]
Cassandra driver jar needs to be put under classpath (reference.conf needs to be found under classpath), currently not sure if the plugin path is under classpath. Now my solution for adding Cassandra driver reference.conf is to put it directly under classpath.

**Comment by imaffe** [comment]
I was trying to solve this Cassandra driver related error. I met this as well when I was testing the driver with a demo project. Stackoverflow says it is because of the netty dependency issue.

error when creating cqlSession java.lang.AbstractMethodError
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.rocketmq.connect.cassandra.common.DBUtils.initCqlSession(DBUtils.java:83)
	at org.apache.rocketmq.connect.cassandra.connector.CassandraSinkTask.start(CassandraSinkTask.java:113)
	at org.apache.rocketmq.connect.runtime.connectorwrapper.WorkerSinkTask.run(WorkerSinkTask.java:263)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.DefaultEventLoopGroup.<init>(DefaultEventLoopGroup.java:58)
	at com.datastax.oss.driver.internal.core.context.DefaultNettyOptions.<init>(DefaultNettyOptions.java:92)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildNettyOptions(DefaultDriverContext.java:463)
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getNettyOptions(DefaultDriverContext.java:806)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.<init>(DefaultSession.java:100)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.init(DefaultSession.java:85)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:665)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:598)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:612)
	at org.apache.rocketmq.connect.cassandra.common.DBUtils$1.call(DBUtils.java:79)
	at org.apache.rocketmq.connect.cassandra.common.DBUtils$1.call(DBUtils.java:76)

**Comment by imaffe** [comment]
WorkerSinkTask#pullMessageFromQueues(), this method can block up to 20 seconds, however the consumer pull timeout is set to 3 seconds, which is very weird.

1. We need to find out why the actual timeout is not the same as the default value, we can do this by adding a try catch block.
