### ISSUE TITLE
[rocketmq-connect-cassandra] CassandraSinkConnector issue recorder

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#561]
Since the official GSoC hasn't begun yet, I'll put some rocketmq-connect-cassandra sink connector related issue here, and will unroll these when official code begins
- [ ] Cassandra datastax driver depends on a netty version conflict with the rocketmq netty dependency.

**Comment by imaffe** [comment]
**Cassandra datastax driver depends on a netty version conflict with the rocketmq netty dependency.**

Using the official non-shaded datastax-java-driver would result in following error message when trying to create a CqlSession

```
Exception in thread "main" java.lang.AbstractMethodError
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.DefaultEventLoopGroup.<init>(DefaultEventLoopGroup.java:58)
        at com.datastax.oss.driver.internal.core.context.DefaultNettyOptions.<init>(DefaultNettyOptions.java:92)
        at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildNettyOptions(DefaultDriverContext.java:463)
        at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
        at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getNettyOptions(DefaultDriverContext.java:806)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.<init>(DefaultSession.java:100)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.init(DefaultSession.java:85)
        at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:665)
        at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:598)
        at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:612)

```

according to 
https://search.maven.org/artifact/com.datastax.oss/java-driver-core-shaded/4.5.1/jar 
and 
https://stackoverflow.com/questions/43145196/exception-while-calling-cassandra-and-elastic-search-from-same-program

we can use this dependency
```
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core-shaded</artifactId>
  <version>4.5.1</version>
</dependency>
```
and it should be good
