### ISSUE TITLE
Failed to query message by Id

### ISSUE THREAD

**Issue by Kcaco01** [apache/rocketmq-externals#572]
Please describe the issue you observed:
What did you do (The steps to reproduce)?
when i wang to query message by rocketmq console

What did you expect to see?
message detail

What did you see instead?
org.apache.rocketmq.console.exception.ServiceException: Failed to query message by Id

Please tell us about your environment:
client: rocketmq-spring-boot-starter-2.1.0
nameserver and broker: 4.7.0

Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
request: http://xxx.xxx.xxx.xxx:8484/message/viewMessage.query?msgId=FE80000000000000B6C3D6E943DA7B1D000018B4AAC211DF987A0004&topic=yxm_order_topic

response: {"status":-1,"data":null,"errMsg":"Failed to query message by Id: FE80000000000000B6C3D6E943DA7B1D000018B4AAC211DF987A0004"}

log：ERROR op=global_exception_handler_print_error
org.apache.rocketmq.console.exception.ServiceException: Failed to query message by Id: FE80000000000000B6C3D6E943DA7B1D000018B4AAC212BFD8240000
	at org.apache.rocketmq.console.service.impl.MessageServiceImpl.viewMessage(MessageServiceImpl.java:70)
	at org.apache.rocketmq.console.controller.MessageController.viewMessage(MessageController.java:49)
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.rocketmq.console.filter.HttpBasicAuthorizedFilter.doFilter(HttpBasicAuthorizedFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fibbery** [comment]
这个其实是rocketmq项目出现的问题，因为在消息内容转换成MessageView的时候，MessageExt的实际实现类是org.apache.rocketmq.common.message.MessageClientExt。代码点：org.apache.rocketmq.console.model.MessageView#fromMessageExt
![image](https://user-images.githubusercontent.com/8580606/83858328-e89b4900-a74e-11ea-8419-bd284eb7f15d.png)
但是MessageExt是把getMsgId重写了的，代码如下：
![image](https://user-images.githubusercontent.com/8580606/83858428-0ff21600-a74f-11ea-9b8a-b63be558ec42.png)
通常情况下，消息会有两个id，一个getOffsetMsgId（就是我们通常意义上说的在broker生成的唯一id)，一个则是在producer端生成的唯一id( 存储在 property中键为UNIQ_KEY的值）
实际上我们一直用的其实是offsetMsgId，我们在broker通过消息id查也是通过这个查询的。这里转换等于直接把一个我们不需要的id转换提供到前端去了。

解决办法有两个，一个是在上述rocketmq-console的类转换处，手工set一下把id改掉，一个是在rocketmq-common项目处更改MessageClientExt的getMsgId方法（目前看不出这个额外类存在的必要）

**Comment by Kcaco01** [comment]
> 这个其实是rocketmq项目出现的问题，因为在消息内容转换成MessageView的时候，MessageExt的实际实现类是org.apache.rocketmq.common.message.MessageClientExt。代码点：org.apache.rocketmq.console.model.MessageView#fromMessageExt
> ![image](https://user-images.githubusercontent.com/8580606/83858328-e89b4900-a74e-11ea-8419-bd284eb7f15d.png)
> 但是MessageExt是把getMsgId重写了的，代码如下：
> ![image](https://user-images.githubusercontent.com/8580606/83858428-0ff21600-a74f-11ea-9b8a-b63be558ec42.png)
> 通常情况下，消息会有两个id，一个getOffsetMsgId（就是我们通常意义上说的在broker生成的唯一id)，一个则是在producer端生成的唯一id( 存储在 property中键为UNIQ_KEY的值）
> 实际上我们一直用的其实是offsetMsgId，我们在broker通过消息id查也是通过这个查询的。这里转换等于直接把一个我们不需要的id转换提供到前端去了。
> 
> 解决办法有两个，一个是在上述rocketmq-console的类转换处，手工set一下把id改掉，一个是在rocketmq-common项目处更改MessageClientExt的getMsgId方法（目前看不出这个额外类存在的必要）

你好，感谢回答。这边你有测试过吗。我这边测试好像不行啊，我这边debug好像是在调用查询接口的时候出错了。如图：
<img width="1111" alt="1" src="https://user-images.githubusercontent.com/48859849/84047497-ebf83400-a9dd-11ea-8770-76e278c333c8.png">

**Comment by duhenglucky** [comment]
@Kcaco01 建议使用MQ admin tools查一下，看下是不是有上述问题。

**Comment by fibbery** [comment]
> > 这个其实是rocketmq项目出现的问题，因为在消息内容转换成MessageView的时候，MessageExt的实际实现类是org.apache.rocketmq.common.message.MessageClientExt。代码点：org.apache.rocketmq.console.model.MessageView#fromMessageExt
> > ![image](https://user-images.githubusercontent.com/8580606/83858328-e89b4900-a74e-11ea-8419-bd284eb7f15d.png)
> > 但是MessageExt是把getMsgId重写了的，代码如下：
> > ![image](https://user-images.githubusercontent.com/8580606/83858428-0ff21600-a74f-11ea-9b8a-b63be558ec42.png)
> > 通常情况下，消息会有两个id，一个getOffsetMsgId（就是我们通常意义上说的在broker生成的唯一id)，一个则是在producer端生成的唯一id( 存储在 property中键为UNIQ_KEY的值）
> > 实际上我们一直用的其实是offsetMsgId，我们在broker通过消息id查也是通过这个查询的。这里转换等于直接把一个我们不需要的id转换提供到前端去了。
> > 解决办法有两个，一个是在上述rocketmq-console的类转换处，手工set一下把id改掉，一个是在rocketmq-common项目处更改MessageClientExt的getMsgId方法（目前看不出这个额外类存在的必要）
> 
> 你好，感谢回答。这边你有测试过吗。我这边测试好像不行啊，我这边debug好像是在调用查询接口的时候出错了。如图：
> <img alt="1" width="1111" src="https://user-images.githubusercontent.com/48859849/84047497-ebf83400-a9dd-11ea-8770-76e278c333c8.png">

调查询接口出错是因为传入的消息id不对，这个存在的问题是，查询消息返回的那个消息id不是真正意义上的消息id，你需要拿的是实际上messageext里面的msgId，而不是unique_key的值
你在view_message这一步已经算是有错了，因为这个消息的消息id根本不对。
你可以根据楼上说的，用mq admin 的 queryMsgById对两个id进行测试就知道了

**Comment by zhoufanshou** [comment]
rocketmq-concosle-ng-1.0.1版本MessageExt没有重写这个msgId，也报了这个错;
而且诡异的是最近的可以正常显示，时间比较久的无法显示

**Comment by liliangzjy** [comment]
用master  JDK1.7

**Comment by zhoufanshou** [comment]
> 用master JDK1.7

现在用的master JDK1.8，请问你遇到过同样的问题吗

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading the to the latest spring-boot. You could use the latest code https://github.com/apache/rocketmq-externals/pull/600. Any question, please feel free to let us know.
