### ISSUE TITLE
exception occurred When I tried to access Aliyun RocketMQ with this console

### ISSUE THREAD

**Issue by fenghaichun** [apache/rocketmq-externals#577]
When I tried to access Alibaba Cloud RocketMQ using this console, the following exception occurred：
```
Caused by: org.apache.rocketmq.client.exception.MQClientException: CODE: 1  DESC: java.lang.NullPointerException, com.alibaba.ons.open.auth.resource.AccessResource.parseAccessResource(AccessResource.java:138)
comp-rocketmq-deepexi-console    | For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicListFromNameServer(MQClientAPIImpl.java:1232)
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.fetchAllTopicList(DefaultMQAdminExtImpl.java:220)
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.fetchAllTopicList(DefaultMQAdminExt.java:183)
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.console.service.client.MQAdminExtImpl.fetchAllTopicList(MQAdminExtImpl.java:147)
comp-rocketmq-deepexi-console    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
comp-rocketmq-deepexi-console    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
comp-rocketmq-deepexi-console    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
comp-rocketmq-deepexi-console    | 	at java.lang.reflect.Method.invoke(Method.java:498)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.console.aspect.admin.MQAdminAspect.aroundMQAdminMethod(MQAdminAspect.java:63)
comp-rocketmq-deepexi-console    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
comp-rocketmq-deepexi-console    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
comp-rocketmq-deepexi-console    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
comp-rocketmq-deepexi-console    | 	at java.lang.reflect.Method.invoke(Method.java:498)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
comp-rocketmq-deepexi-console    | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
comp-rocketmq-deepexi-console    | 	at com.sun.proxy.$Proxy71.fetchAllTopicList(Unknown Source)
comp-rocketmq-deepexi-console    | 	at org.apache.rocketmq.console.task.DashboardCollectTask.collectTopic(DashboardCollectTask.java:79)
comp-rocketmq-deepexi-console    | 	... 32 common frames omitted
```
Here is the docker-compose.yml:
```
version: '3.7'

services:

  comp-rocketmq-deepexi-console:
      image: styletang/rocketmq-console-ng
      container_name: comp-rocketmq-deepexi-console
      network_mode: host
      ports:
       - 9093:8080
      environment:
       - JAVA_OPTS=-Drocketmq.config.namesrvAddr=MQ_INSTxxxxx.cn-shanghai.mq-internal.aliyuncs.com:8080 -Drocketmq.consume.access-key=XXX -Drocketmq.consume.secret-key=xxx

```

Does this console support access to Alibaba Cloud RocketMQ? How do I access it?  please help me, thanks.

**Comment by fenghaichun** [comment]
反反复复

**Comment by captainkun** [comment]
Hi,could you tell me how you solved it?

**Comment by fenghaichun** [comment]
> Hi,could you tell me how you solved it?

no, I didn't solved it.

**Comment by captainkun** [comment]
I know the reason:this exporter only for open-source rocketmq versions.
you can look at:https://github.com/apache/rocketmq-exporter/issues/27

**Comment by fenghaichun** [comment]
> I know the reason:this exporter only for open-source rocketmq versions.
> you can look at:[apache/rocketmq-exporter#27](https://github.com/apache/rocketmq-exporter/issues/27)

yes，I guess it's the reason, thanks.
