### ISSUE TITLE
pom 版本依赖存在bug

### ISSUE THREAD

**Issue by brucelwl** [apache/rocketmq-externals#689]
我修改了版本之后就好了, 这代码提交的估计都没测试吧
```
[2021-03-14 21:22:53.321] ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.NoClassDefFoundError: 
	at io.micrometer.core.instrument.AbstractTimer.initPauseDetector(AbstractTimer.java:97)
	at io.micrometer.core.instrument.AbstractTimer.<init>(AbstractTimer.java:81)
	at io.micrometer.core.instrument.cumulative.CumulativeTimer.<init>(CumulativeTimer.java:43)
	at io.micrometer.core.instrument.simple.SimpleMeterRegistry.newTimer(SimpleMeterRegistry.java:87)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:271)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:576)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:269)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:477)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.getTimer(WebMvcMetricsFilter.java:181)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.record(WebMvcMetricsFilter.java:143)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:115)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
```

**Comment by vongosling** [comment]
请细化你的问题，并修改你的题目为英文，按照模板回答什么项目，做了什么操作。如果是console，非常欢你来尝试补充测试，包括集成测试。
